apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes: [ReadWriteOnce]
  hostPath:
    path: /var/lib/postgresql/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: default
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes: [ReadWriteOnce]
