services:

  jenkins:
    restart: always
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - WHANOS_REGISTRY=localhost:5000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/.kube/config:/var/jenkins_home/.kube/config"

  registry:
    restart: always
    image: registry:2
    ports:
      - "5000:5000"
