name: hal
version: 0.1.0.0
github: "huntears/hal"
license: GPL-3
author: "huntears"
maintainer: "dev@huntears.com"
copyright: "2021 huntears"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/huntears/hal#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - containers

executables:
  hal-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hal

tests:
  hal-test:
    main: TestJaarse.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hal
      - HUnit
