name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  apply_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Install k3s
      run: |
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh -
        cat /etc/rancher/k3s/k3s.yaml
        mkdir -p ~/.kube
        cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
    - name: Get cluster info
      run: |
        kubectl cluster-info
    - name: Apply deployment
      run: |
        ./applyDeploy.sh
    - name: Get last infos
      run: |
        kubectl get pods
        kubectl get nodes
        kubectl get deployments
        kubectl get services
        kubectl get events